# Generated by Django 5.0.2 on 2024-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_referal_validity_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='created_data',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата создания кода'),
        ),
        migrations.AlterField(
            model_name='referal',
            name='end_life',
            field=models.DateField(db_index=True, verbose_name='Окончание работы кода'),
        ),
    ]
