# Generated by Django 5.0.2 on 2024-02-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_referal_created_data_alter_referal_end_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='created_data',
            field=models.DateField(db_index=True, verbose_name='Дата создания кода'),
        ),
    ]
