# Generated by Django 2.2.19 on 2024-02-19 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Реферальная ссылка')),
                ('created_data', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания ссылки')),
                ('validity_period', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Срок действия ссылки')),
            ],
            options={
                'ordering': ('-created_data',),
            },
        ),
    ]
