# Generated by Django 2.2.19 on 2024-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referal_code',
            field=models.CharField(max_length=200, null=True, verbose_name='Реферальная ссылка'),
        ),
    ]
